routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function()
{
    Route::resource('employee', 'EmployeeController');
    
    Route::resource('upload', 'UploadController');
    
    Route::post('upload/create', 'UploadController@create');
    
    Route::get('servicebook/search', 'UploadController@search');
    
    Route::post('servicebook/search', 'UploadController@searchresult');
    
    Route::get('servicebook/download/{id}', 'UploadController@download');

    /*Route::group(['namespace' => 'Admin'], function() {
        Route::group(['middleware' => ['role:admin']], function()
        {
            Route::resource('admin/users', 'UsersController');
        });
    });
    
    Route::group(['middleware' => ['role:admin,operator']], function()
    {
        Route::resource('doctors', 'DoctorsController');
            
        Route::get('searchpatient', 'PatientController@ShowSearch');
            
        Route::get('searchpatientform', 'PatientController@SearchPatient');
            
        Route::get('showreferred/{id}', 'PatientController@ShowReferredPatient');
        
        Route::post('updatereferred/{id}', 'PatientController@ReferredPatientEntry');
        
        Route::get('newpatient', 'PatientController@ShowNewPatientForm');
        
        Route::post('newpatient', 'PatientController@ReferPatientAdmin');
    });*/
    
});

app/Upload.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Upload extends Model
{
    public function employee()
    {
        return $this->belongsTo('App\Employee');
    }
}

app/Http/Controllers/UploadController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Employee;
use App\Upload;
use Storage;
use Log;

class UploadController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('upload.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $emp_no = $request->input('emp_no');
        
        $employee = Employee::where('emp_no', $emp_no)
                            ->first();
        
        if(!$employee) {
            return redirect()->back()->with(['msg' => ['Employee not found']]);
        }
        
        return view('upload.create')->with(['emp_no' => $emp_no, 'employee_name' => $employee->name]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
			'emp_no' => 'required',
			'file.*' => 'file',
		]);
		
		$emp_no = $request->input('emp_no');
		$tags = $request->input('tags');
		
		$employee_id = Employee::where('emp_no', $emp_no)
		                        ->first()->id;
		
		foreach($request->file('file') as $key=>$file) {
		    if($file){
				$path = $file->getRealPath();
				$originalName = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
				$extension = strtolower($file->getClientOriginalExtension()); // get extension
				$fileName = snake_case($originalName.'_'.time().'.'.$extension); // renaming image
                
                $upload = new Upload;
		        $upload->employee_id = $employee_id;
		        $upload->filename = $fileName;
		        $upload->tags = $tags[$key];
		        $upload->save();
                
                $path = Storage::disk('servicebooks')->putFileAs(
                    $upload->id, $file, $fileName
                );
                
                $url = Storage::disk('servicebooks')->url($path);
                
                $upload->url = $url;
                $upload->save();
		    }
		}
		
		return redirect('/upload')->with(['msg' => ['Service book uploaded successfully...']]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $upload = Upload::find($id);
        Storage::disk('servicebooks')->delete($upload->id.'/'.$upload->filename);
        Storage::disk('servicebooks')->deleteDirectory($upload->id);
        Upload::destroy($id);
    }
    
    public function search(){
        return view('upload.search');
    }
    
    public function searchresult(Request $request){
        $this->validate($request, [
			'emp_no' => 'required',
		]);
		
		$emp_no = $request->input('emp_no');
		$tags = $request->input('tags');
		
		$employee = Employee::where('emp_no', $emp_no)
		                    ->first();
		
		if(!$employee) {
            return redirect()->back()->with(['msg' => ['No employee found...']]);
        }
		
		$searchValues = preg_split('/\s+/', $tags, -1, PREG_SPLIT_NO_EMPTY);
		
		$upload = Upload::where('employee_id', $employee->id)
		                ->where(function ($q) use ($searchValues) {
                          foreach ($searchValues as $value) {
                            $q->orWhere('tags', 'like', "%{$value}%");
                          }
                        })
                        ->orderBy('created_at', 'desc')
                        ->get();
        
        if(!$upload->count()) {
            return redirect()->back()->with(['msg' => ['No results found...']]);
        }
        
        $data = ['upload' => $upload, 'employee' => $employee];
        
        return view('upload.searchresults')->with($data);
        
    }
    
    public function download($id)
    {
        $upload = Upload::find($id);
        return Storage::disk('servicebooks')->download($upload->id.'/'.$upload->filename);
    }
}

resources/views/upload/create.blade.php
@extends('AdminLTE.admin_template')

@section('page-title', 'Upload Service Books')

@section('title', 'Upload Service Books of '.$employee_name.' ('.$emp_no.')')

@section('css')
  @parent
<link rel="stylesheet" href="/css/selectize.bootstrap3.css" type="text/css" />
@endsection

@section('content')
<div class="row">
    <form action="/upload" method="post" class="form-horizontal" enctype="multipart/form-data">
      @csrf
      <input type="hidden" name="emp_no" value="{{ $emp_no }}"/>
    <!-- Main content -->
        <div class="col-md-12">
          <!-- Horizontal Form -->
          <div class="box box-info">
            <!--<div class="box-header with-border">
              <h3 class="box-title"></h3>
            </div>-->
            <!-- /.box-header -->
            <!-- form start -->
            
              <div class="box-body" id="field-wrapper">
                <div class="form-group">
                  <label class="col-md-2 control-label">Upload Service Book</label>
                  <div class="row">
                    <div class="col-md-3">
                        <input type="file" name="file[]" class="form-control">
                    </div>
                    <div class="col-md-6">
                        <input id="sel-0" type="text" name="tags[]" class="form-control" tabindex="-1" placeholder="Enter file tags">
                    </div>
                  </div>
                </div>
              </div>

              </div>   
        </div>
              <!-- /.box-body -->
        <div class="box-footer">
          <input type="hidden" name="MAX_FILE_SIZE" value="5000000">
          <button type="submit" class="btn btn-info">Submit</button>
          <button type="button" id="addMore" class="btn btn-primary pull-right">Add More</button>
        </div>
              <!-- /.box-footer -->
    </form>
</div>
@endsection

@section('js')
  @parent
<script type="text/javascript" src="/js/selectize.min.js"></script>
<script type="text/javascript">
  $('document').ready(function(){
    var i=1;
    $('#addMore').on('click', function(e){
      const field = '<div class="form-group"><label class="col-md-2 control-label">Upload Service Book</label><div class="row"><div class="col-md-3"><input type="file" name="file[]" class="form-control"></div><div class="col-md-6"><input id="sel-' + i + '" type="text" name="tags[]" class="form-control" tabindex="-1" placeholder="Enter file tags"></div></div></div>';
      $('#field-wrapper').append(field);
      selectize('#sel-' + i);
      i=i+1;
    });
    
    /*---------------tags--------------------------*/
	  selectize('#sel-0');
	  
	  function selectize(selector) {
	    $(selector).selectize({
    		delimiter: ',',
    		persist: false,
    		create: function(input) {
    			return {
    				value: input,
    				text: input
    			}
    		}
    	});
	  }
  	
  })
</script>
@endsection

resources/views/upload/index.blade.php
@extends('AdminLTE.admin_template')

@section('page-title', 'Upload Service Book')

@section('title', 'Enter Employee Id')

@section('content')
<!-- message --->
@include('layouts.messages')
            <form method="POST" action="/upload/create">
            @csrf
            <div class="col-md-6">
            <div class="input-group">
              <input name="emp_no" type="text" class="form-control" placeholder="Employee Id">
              <span class="input-group-btn">
                <button class="btn btn-default" type="submit">Search</button>
              </span>
            </div><!-- /input-group -->
            </div>
          </form>
@endsection

resources/views/upload/search.blade.php
@extends('AdminLTE.admin_template')

@section('page-title', 'Search Service Books')

@section('title', 'Search Service Books')

@section('content')
<form class="form-horizontal" action="/servicebook/search" method="post">
    @csrf
    <div class="row">
<!-- message --->
@include('layouts.messages')
    <!-- Main content -->
          <!-- Horizontal Form -->
        <div class="box box-info">
            <!--<div class="box-header with-border">
              <h3 class="box-title">View Service Book</h3>
            </div>-->
            <!-- /.box-header -->
            <!-- form start -->
            <div class="box-body">
                <div class="form-group">
                    <label for="emp-id" class="col-sm-2 control-label">Employee Id</label>
                    <div class="col-md-5">
                      <div class="input-group">
                        <div class="input-group-addon">
                          <i class="fa fa-vcard-o"></i>
                        </div>
                      <input name="emp_no" type="text" class="form-control" id="" placeholder="" required>
                      </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="emp-id" class="col-sm-2 control-label">Tag</label>
                    <div class="col-md-5">
                      <div class="input-group">
                        <div class="input-group-addon">
                          <i class="fa fa-tags"></i>
                        </div>
                      <input name="tags" type="text" class="form-control" id="" placeholder="">
                      </div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
            <!-- box-footer -->
            <div class="box-footer">
                <button type="submit" class="btn btn-info">Search</button>
            </div>
            <!-- /.box-footer -->
        </div>
    </div>
</form>
@endsection

resources/views/upload/searchresults.blade.php
@extends('AdminLTE.admin_template')

@section('page-title', 'Search Service Books')

@section('title', 'Search Service Books')

@section('content')
<div class="box box-info">
<div class="box-body table-responsive">
              <table id="allDataTable" class="table table-hover table-bordered" cellspacing="0" width="100%">
                  <thead>
                <tr>
                  <th>File</th>
                  <th>Upload Date</th>
                  <th>Tags</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
    @foreach($upload as $key=>$file)
                <tr>
                  <td><a href="{{ asset($file->url) }}" target="_blank">{{ $file->filename }}</a></td>
                  <td>{{ $file->created_at }}</td>
                  <td>{{ $file->tags }}</td>
                  <td><a target="_blank" class="btn btn-primary" href="{{ url('/servicebook/download/'.$file->id) }}" role="button" title="Download">
					<span class="glyphicon glyphicon-download" aria-hidden="true"></span>
				</a> <a class="delBtn btn btn-danger" href="#" data-href="{{ route('upload.destroy', ['id' => $file->id]) }}" role="button" title="Delete">
					<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
				</a></td>
                </tr>
    @endforeach
    </tbody>
            </table>
</div>
</div>
@endsection

@section('js')
<script type="text/javascript" src="/js/jquery.confirm.min.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
		$(document).on('click', '.delBtn', function(event){
			event.preventDefault();
			var url = $(this).data("href");
			$.confirm({
				text: "Confirm deletion",
			    confirm: function() {
			        $.ajax({
					    url: url,
					    headers: {'X-CSRF-TOKEN': '{{csrf_token()}}'},
					    type: 'DELETE',
					    success: function(result) {
					        window.location.reload();
					    }
					});
			    },
			    cancel: function() {
			        // nothing to do
			    },
			    confirmButton: "Yes",
			    cancelButton: "No",
			    post: true,
			    confirmButtonClass: "btn-danger",
			    cancelButtonClass: "btn-default",
			    dialogClass: "modal-dialog modal-sm"
			});
		});

		var table = $('#allDataTable').DataTable();

	});
</script>
@endsection