routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function()
{
    Route::resource('employee', 'EmployeeController');
    
    Route::resource('upload', 'UploadController');
    
    Route::post('upload/create', 'UploadController@create');
    
    Route::get('servicebook/search', 'UploadController@search');
    
    Route::post('servicebook/search', 'UploadController@searchresult');
    
    Route::get('servicebook/download/{id}', 'UploadController@download');

    /*Route::group(['namespace' => 'Admin'], function() {
        Route::group(['middleware' => ['role:admin']], function()
        {
            Route::resource('admin/users', 'UsersController');
        });
    });
    
    Route::group(['middleware' => ['role:admin,operator']], function()
    {
        Route::resource('doctors', 'DoctorsController');
            
        Route::get('searchpatient', 'PatientController@ShowSearch');
            
        Route::get('searchpatientform', 'PatientController@SearchPatient');
            
        Route::get('showreferred/{id}', 'PatientController@ShowReferredPatient');
        
        Route::post('updatereferred/{id}', 'PatientController@ReferredPatientEntry');
        
        Route::get('newpatient', 'PatientController@ShowNewPatientForm');
        
        Route::post('newpatient', 'PatientController@ReferPatientAdmin');
    });*/
    
});

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $table = 'employee';
    
    public function upload()
    {
        return $this->hasMany('App\Upload');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Employee;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::all();
        
		$data = ['employees' => $employees];
		return view('employee.index')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('employee.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
			'name' => 'required',
			'emp_no' => 'required'
		]);
		
		$employee = new Employee;
		$employee->name = $request->input('name');
		$employee->emp_no   = $request->input('emp_no');
		$employee->dob = $request->input('dob');
		$employee->designation = $request->input('designation');
		$employee->appointment_date = $request->input('appointment_date');
		$employee->department = $request->input('department');
		$employee->save();
		
		$data = [ "msg" => ["Employee added successfully"] ];
		
		return redirect('employee')->with($data);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Employee::destroy($id);
    }
}

resources/views/employee/create.blade.php
@extends('AdminLTE.admin_template')

@section('page-title', 'Enter Employee Details')

@section('title', 'Enter Employee Details')

@section('content')
    <div class="row">
        <div class="col-md-8">
                  <div class="col-md-12">
          <!-- Horizontal Form -->
          <div class="box box-info">
            <!--<div class="box-header with-border">
              <h3 class="box-title">Enter Servicemen Details</h3>
            </div>-->
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" action="/employee" method="POST">
                @csrf
              <div class="box-body">
                <div class="form-group">
                    <label for="emp-id" class="col-sm-2 control-label">Employee Id</label>

                    <div class="col-sm-10">
                      <div class="input-group">
                        <div class="input-group-addon">
                          <i class="fa fa-vcard-o"></i>
                        </div>
                      <input name="emp_no" type="text" class="form-control" id="" placeholder="">
                      </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="name" class="col-sm-2 control-label">Name</label>

                    <div class="col-sm-10">
                      <div class="input-group">
                        <div class="input-group-addon">
                          <i class="fa fa-user-circle"></i>
                        </div>
                      <input name="name" type="text" class="form-control" id="" placeholder="">
                      </div>
                    </div>
                </div>
                <div class="form-group">
                  <label for="dob" class="col-sm-2 control-label">Date of Birth</label>

                  <div class="col-sm-10">
                      <div class="input-group">
                        <div class="input-group-addon">
                          <i class="fa fa-calendar"></i>
                        </div>
                        <input name="dob" type="date" class="form-control">
                      </div>
                  </div>
                </div>
                <div class="form-group">
                    <label for="designation" class="col-sm-2 control-label">Designation</label>

                    <div class="col-sm-10">
                      <div class="input-group">
                        <div class="input-group-addon">
                          <i class="fa fa-dot-circle-o"></i>
                        </div>
                          <input name="designation" type="text" class="form-control" id="" placeholder="">
                      </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="department" class="col-sm-2 control-label">Department</label>

                    <div class="col-sm-10">
                      <div class="input-group">
                        <div class="input-group-addon">
                          <i class="fa fa-institution"></i>
                        </div>
                          <input name="department" type="text" class="form-control" id="" placeholder="">
                      </div>
                    </div>
                </div>

                <div class="form-group">
                  <label for="doa" class="col-sm-2 control-label">Date of Appointment</label>

                  <div class="col-sm-10">
                      <div class="input-group">
                        <div class="input-group-addon">
                          <i class="fa fa-calendar"></i>
                        </div>
                        <input name="appointment_date" type="date" class="form-control" id="">
                      </div>
                  </div>
                </div>

              </div>   
            </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <button type="submit" class="btn btn-info">Submit</button>
              </div>
              <!-- /.box-footer -->
            </form>
          </div>
        </div>
    </div>
@endsection

resources/views/employee/index.blade.php
@extends('AdminLTE.admin_template')

@section('page-title', 'View Employees')

@section('title', 'View Employees')

@section('content')
<!-- message --->
@include('layouts.messages')
<div class="box">
	<div class="box-header">
        <!--<h3 class="box-title">Hover Data Table</h3>-->
    </div>
    <div class="box-body">
<div class="table-responsive">
<table id="allDataTable" class="table table-bordered table-hover" cellspacing="0" width="100%">
	<thead>
		<tr>
			<th>Sl</th>
			<th>Employee Name</th>
			<th>Employee Id</th>
			<th>Date of Birth</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
@foreach ($employees as $key=>$employee)
		<tr>
			<td>{{ ($key+1) }}</td>
			<td>{{ $employee->name }}</td>
			<td>{{ $employee->emp_no }}</td>
			<td>{{ $employee->dob }}</td>
			<td>
				<a class="btn btn-default" href="{{ route('employee.edit', ['id' => $employee->id]) }}" role="button" title="Edit">
					<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
				</a>
				<a class="delBtn btn btn-danger" href="#" data-href="{{ route('employee.destroy', ['id' => $employee->id]) }}" role="button" title="Delete">
					<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
				</a>
			</td>
		</tr>
@endforeach
	</tbody>
</table>
</div>
</div>
</div>
@endsection

@section('js')
<script type="text/javascript" src="/js/jquery.confirm.min.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
		$(document).on('click', '.delBtn', function(event){
			event.preventDefault();
			var url = $(this).data("href");
			$.confirm({
				text: "Confirm deletion",
			    confirm: function() {
			        $.ajax({
					    url: url,
					    headers: {'X-CSRF-TOKEN': '{{csrf_token()}}'},
					    type: 'DELETE',
					    success: function(result) {
					        window.location.reload();
					    }
					});
			    },
			    cancel: function() {
			        // nothing to do
			    },
			    confirmButton: "Yes",
			    cancelButton: "No",
			    post: true,
			    confirmButtonClass: "btn-danger",
			    cancelButtonClass: "btn-default",
			    dialogClass: "modal-dialog modal-sm"
			});
		});

		var table = $('#allDataTable').DataTable({
    		"aaSorting": [[ 0, "desc" ]],
    	});

	});
</script>
@endsection